### ISSUE TITLE
Add "How to add PHPStan extensions" part to the README

### ISSUE THREAD

**Issue by tommy-muehle** [phpstan/docker-image#21]
We should add a part about how to add a PHPStan extension, such as "phpstan-phpunit", to the README.

**Comment by Soullivaneuh** [comment]
@tommy-muehle Could you please to add some explanation here? I'm trying to use phpstan-symfony:

```yaml
parameters:
    includes:
        - ./vendor/lookyman/phpstan-symfony/extension.neon
    parameters:
        symfony:
            container_xml_path: ./var/cache/dev/appDevDebugProjectContainer.xml
```

But it seems to have no effect.
